apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rh-quiz-data
  labels:
    app: rh-quiz
    app.kubernetes.io/name: rh-quiz
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
