apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: rh-quiz
  labels:
    app: rh-quiz
    app.kubernetes.io/name: rh-quiz
    app.kubernetes.io/component: build
spec:
  output:
    to:
      kind: ImageStreamTag
      name: rh-quiz:latest
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  triggers: []
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: rh-quiz
  labels:
    app: rh-quiz
    app.kubernetes.io/name: rh-quiz
